title: Stack Problems
description: My Personal Stack Problems
author: Grom(巴林的狗尾草)
github: http://git.oschina.net/grom
about: The architect of JAVA, currently doing more in backend.
url:         # the base hostname & protocol for your site
urls:
    - text: About Me
      url: /about/
    - text: Github_cn
      url: http://git.oschina.net/grom
    - text: XML Feed
      url: /feed.xml
url: "https://evergreen-tree.github.io"
baseurl: ""
gems: [jekyll-paginate]
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Grom(巴林的狗尾草)
  avatar: avatar.jpg
  job: "JAVA architect"
  bio: "The architect of JAVA, currently doing more in backend."
  email: wenbindong1984@163.com
  disqus-shortname:
  twitter:
  facebook:
  google:
    plus:
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
